services:
  modular_service:
    build:
      context: ./
      dockerfile: modular.Dockerfile
    image: cuda:12.8
    container_name: cuda128
    network_mode: host
    environment:
      - HF_HOME=/data/hf_home
      - UV_CACHE_DIR
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /data/pavan/opensource/mojos
        target: /data/pavan/opensource/mojos
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: /data/docker/conda_containers
        target: /data/docker/conda_containers
      - type: bind
        source: /data/hf_home
        target: /data/hf_home
      - type: bind
        source: /data/docker/uv_containers
        target: /data/docker/uv_containers
      
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    security_opt:
      - apparmor:unconfined
    ipc: host
    
    stdin_open: true 
    tty: true

    # Uncomment if below doesnt work
    # runtime: nvidia
    # default choice
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
