services:
  mojo_service:
    build:
      context: ./
      dockerfile: Dockerfile.mojosdk
    image: mojo:v2
    container_name: mojov2
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /data/nvidia_local/opensource/mojos
        target: /data/nvidia_local/opensource/mojos
      - type: bind
        source: /data
        target: /data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    security_opt:
      - apparmor:unconfined
    ipc: host
    
    stdin_open: true 
    tty: true

    # Uncomment if below doesnt work
    # runtime: nvidia
    # default choice
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
