FROM ubuntu:22.04

RUN apt-get update \
#    && DEBIAN_FRONTEND=noninteractive TZ=$DEFAULT_TZ apt-get install -y \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        tzdata \
        vim \
        nano \
        sudo \
        curl \
        wget \
        git && \
        rm -rf /var/lib/apt/lists/*

RUN curl -ssL https://magic.modular.com/a2d09ad7-8f5a-4157-8032-6462ac885e8c | bash
# Set the entry point to bash
ENTRYPOINT ["/bin/bash"]
